"""Generate hreflang link tags for fr-FR/fr-BE/fr-CH market expansion."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import click
from rich.console import Console

from scripts._config import get_config

console = Console()


def _url_paths_from_snapshot(snapshot_path: str) -> list[dict[str, str]]:
    """Extract URL paths and page types from Shopify snapshot.

    Returns:
        List of dicts with keys: path, page_type, title.
    """
    with open(snapshot_path, encoding="utf-8") as f:
        data = json.load(f)

    pages: list[dict[str, str]] = [{"path": "/", "page_type": "homepage", "title": "Homepage"}]

    for product in data.get("products", []):
        if product["title"].startswith("Pet ") or product["title"].endswith("(test)"):
            continue
        handle = product.get("handle", "")
        if handle:
            pages.append(
                {
                    "path": f"/products/{handle}",
                    "page_type": "product",
                    "title": product.get("title", handle),
                }
            )

    for collection in data.get("collections", []):
        handle = collection.get("handle", "")
        if handle:
            pages.append(
                {
                    "path": f"/collections/{handle}",
                    "page_type": "collection",
                    "title": collection.get("title", handle),
                }
            )

    return pages


def build_hreflang_entries(
    pages: list[dict[str, str]],
    base_url: str,
    locales: list[tuple[str, str]],
) -> list[dict[str, Any]]:
    """Build hreflang link data for every page × locale combination.

    Args:
        pages: List of page dicts with path, page_type, title.
        base_url: Canonical base URL (e.g. https://www.leoniedelacroix.com).
        locales: List of (hreflang, url_prefix) tuples.

    Returns:
        List of page entries, each with a list of hreflang link dicts.
    """
    entries: list[dict[str, Any]] = []

    for page in pages:
        path = page["path"]
        links: list[dict[str, str]] = []

        for hreflang, prefix in locales:
            # fr generic fallback points to the canonical (no prefix)
            effective_prefix = "" if hreflang == "fr" else prefix
            url = f"{base_url}{effective_prefix}{path}"
            links.append({"hreflang": hreflang, "url": url})

        # x-default always points to the canonical (fr-FR) URL
        canonical_url = f"{base_url}{path}"
        links.append({"hreflang": "x-default", "url": canonical_url})

        entries.append(
            {
                "path": path,
                "page_type": page["page_type"],
                "title": page["title"],
                "links": links,
            }
        )

    return entries


def render_liquid_snippet(entries: list[dict[str, Any]]) -> str:
    """Render a Shopify Liquid snippet for hreflang tags.

    Returns a string to paste inside the <head> of theme.liquid.
    The snippet uses Liquid's request.path to match the current URL.
    """
    lines = [
        "{%- comment -%}",
        "  hreflang tags — generated by leonie-seo pipeline",
        "  Paste inside <head> in theme.liquid",
        "{%- endcomment -%}",
        "",
        "{%- assign current_path = request.path -%}",
        "",
    ]

    # For each page, output a conditional block
    for entry in entries:
        path = entry["path"]
        condition = "request.page_type == 'index'" if path == "/" else f"current_path == '{path}'"
        lines.append(f"{{% if {condition} %}}")
        for link in entry["links"]:
            lines.append(
                f'  <link rel="alternate" hreflang="{link["hreflang"]}" href="{link["url"]}">'
            )
        lines.append("{% endif %}")
        lines.append("")

    return "\n".join(lines)


def render_sitemap_xml(entries: list[dict[str, Any]]) -> str:
    """Render hreflang xhtml:link entries for sitemap XML."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
        "",
    ]
    for entry in entries:
        lines.append("  <url>")
        # Canonical URL as <loc>
        canonical = next(lnk["url"] for lnk in entry["links"] if lnk["hreflang"] == "x-default")
        lines.append(f"    <loc>{canonical}</loc>")
        for link in entry["links"]:
            lines.append(
                f'    <xhtml:link rel="alternate" hreflang="{link["hreflang"]}" href="{link["url"]}"/>'
            )
        lines.append("  </url>")
        lines.append("")

    lines.append("</urlset>")
    return "\n".join(lines)


def render_markdown(
    entries: list[dict[str, Any]],
    locales: list[tuple[str, str]],
    date: str,
    liquid_snippet: str,
    site: str | None = None,
) -> str:
    """Render hreflang report as Markdown."""
    from scripts._config import get_config

    site_label = site or get_config().domain
    products = [e for e in entries if e["page_type"] == "product"]
    collections = [e for e in entries if e["page_type"] == "collection"]
    locale_tags = ", ".join(f"`{h}`" for h, _ in locales)

    lines = [
        f"# Balises Hreflang — {site_label} — {date}",
        "",
        "## Résumé",
        "",
        f"**{len(entries)} pages** couvertes · Locales : {locale_tags} + `x-default`",
        f"- Produits : {len(products)}",
        f"- Collections : {len(collections)}",
        f"- Autres : {len(entries) - len(products) - len(collections)}",
        "",
        "> Les balises hreflang indiquent à Google quelle version servir selon la localisation",
        "> de l'utilisateur. Indispensable lors d'une expansion BE/CH pour éviter le duplicate content.",
        "",
        "---",
        "",
        "## URLs couvertes",
        "",
        "| Page | Type | Locales générées |",
        "|---|---|---|",
    ]

    locale_count = len(locales) + 1  # +1 for x-default
    for entry in entries[:30]:  # cap table at 30 rows for readability
        lines.append(f"| `{entry['path']}` | {entry['page_type']} | {locale_count} balises |")
    if len(entries) > 30:
        lines.append(f"| … | … | {len(entries) - 30} pages supplémentaires |")

    lines += [
        "",
        "---",
        "",
        "## Intégration Shopify",
        "",
        "### 1. Snippet Liquid — coller dans `<head>` de `theme.liquid`",
        "",
        "```liquid",
        liquid_snippet[:3000],  # truncate for readability in report
        "```",
        "",
        "> **Note** : pour un catalogue > 50 produits, préférer une section Liquid dynamique",
        "> basée sur `canonical_url` plutôt que des blocs if/endif statiques.",
        "",
        "### 2. Activer les marchés Shopify",
        "",
        "1. **Admin Shopify** → Paramètres → Marchés → Ajouter un marché",
        "2. Créer `Belgique (fr-BE)` et `Suisse (fr-CH)` avec sous-chemin `/fr-be/` et `/fr-ch/`",
        "3. Le snippet Liquid ci-dessus génère automatiquement les bonnes URLs",
        "",
        "### 3. Vérification",
        "",
        "```bash",
        "# Vérifier les balises sur la homepage",
        f"curl -s https://{site_label} | grep 'hreflang'",
        "```",
        "",
        "---",
        "",
        f"*Généré automatiquement par le pipeline SEO {site_label}*",
    ]
    return "\n".join(lines)


@click.command()
@click.option("--snapshot", default="data/raw/shopify_snapshot.json", show_default=True)
@click.option("--base-url", default=None, help="Override base URL (default: from tenant config)")
@click.option("--output-dir", default="reports", show_default=True)
@click.option("--json-output", default="data/raw/hreflang.json", show_default=True)
@click.option("--sitemap-output", default="data/raw/hreflang_sitemap.xml", show_default=True)
@click.option("--tenant", default=None, help="Tenant ID (default: TENANT_ID env var)")
def main(
    snapshot: str,
    base_url: str | None,
    output_dir: str,
    json_output: str,
    sitemap_output: str,
    tenant: str | None,
) -> None:
    """Generate hreflang tags for fr-FR/fr-BE/fr-CH market expansion."""
    cfg = get_config(tenant)
    effective_base_url = base_url or cfg.base_url
    locales = cfg.hreflang_locales_as_tuples()

    console.print("[bold cyan]► Generating hreflang tags[/bold cyan]")

    pages = _url_paths_from_snapshot(snapshot)
    entries = build_hreflang_entries(pages, effective_base_url, locales)

    console.print(f"  {len(entries)} pages × {len(locales) + 1} locales")

    Path(json_output).parent.mkdir(parents=True, exist_ok=True)
    with open(json_output, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    sitemap = render_sitemap_xml(entries)
    Path(sitemap_output).write_text(sitemap, encoding="utf-8")

    liquid = render_liquid_snippet(entries)
    date = datetime.now(UTC).strftime("%Y-%m-%d")
    out_dir = Path(output_dir) / date
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "hreflang.md"
    out_path.write_text(render_markdown(entries, locales, date, liquid), encoding="utf-8")

    console.print(f"  [green]✓[/green] {len(entries)} pages → {out_path}")
    console.print(f"  [green]✓[/green] Sitemap XML → {sitemap_output}")
    console.print(f"  [green]✓[/green] JSON → {json_output}")


if __name__ == "__main__":
    main()
