"""Build the unified Diff preview object from a ContentActionResult."""

from __future__ import annotations

from pathlib import Path

from app.content_actions.runner import _load_action
from app.content_actions.schema import ContentType


def _blocked_reasons(constraints_check) -> list[str]:
    reasons: list[str] = []
    if constraints_check.forbidden_promise_violations:
        reasons.append(
            "forbidden_promise: " + ", ".join(constraints_check.forbidden_promise_violations)
        )
    if constraints_check.do_not_say_violations:
        reasons.append(
            "do_not_say: " + ", ".join(constraints_check.do_not_say_violations)
        )
    if not constraints_check.length_ok:
        reasons.append("length_out_of_bounds")
    if not constraints_check.language_ok:
        reasons.append("language_mismatch")
    return reasons


def _type_label_fr(content_type: ContentType) -> str:
    return {
        ContentType.META_TITLE: "titre méta",
        ContentType.META_DESCRIPTION: "description méta",
        ContentType.PRODUCT_DESCRIPTION: "description produit",
        ContentType.COLLECTION_DESCRIPTION: "description de collection",
        ContentType.ALT_TEXT: "texte alternatif",
        ContentType.FAQ_BLOCK: "FAQ",
        ContentType.ANSWER_BLOCK: "bloc de réponse",
        ContentType.BUYING_GUIDE: "guide d'achat",
        ContentType.JSONLD_FAQPAGE: "données structurées JSON-LD",
        ContentType.META_MULTILINGUAL: "méta multilingue",
    }.get(content_type, content_type.value)


def _merchant_summary_fr(
    content_type: ContentType,
    resource_id: str,
    quality_score: int,
) -> str:
    label = _type_label_fr(content_type)
    q_label = (
        "très bien noté" if quality_score >= 85
        else "bien noté" if quality_score >= 65
        else "à compléter" if quality_score >= 45
        else "incomplet"
    )
    return (
        f"Nouveau {label} généré pour « {resource_id} » — "
        f"score qualité {quality_score}/100 ({q_label}). "
        f"Vérifiez le contenu avant de l'appliquer à votre boutique."
    )


def build_diff(
    action_id: str,
    shop: str,
    *,
    db_path: Path | None = None,
) -> dict | None:
    """Build the review Diff object for a content action.

    Args:
        action_id: ID of the content action.
        shop: Shopify shop domain.
        db_path: Optional DB path override (tests only).

    Returns:
        Diff dict, or None if the action is not found.
    """
    result = _load_action(shop, action_id, db_path=db_path)
    if result is None:
        return None

    blocked = _blocked_reasons(result.constraints_check)
    if not blocked:
        next_actions = ["accept", "edit", "reject", "retry"]
    else:
        next_actions = ["edit", "reject", "retry"]

    return {
        "action_id": action_id,
        "content_type": result.content_type.value,
        "resource": {
            "id": result.resource_id,
            "handle": result.resource_id,
            "title": result.resource_id,
        },
        "before": None,
        "after": {
            "primary_text": result.output.primary_text,
            "structured": result.output.structured if hasattr(result.output, "structured") else None,
        },
        "facts_used": [f.model_dump() for f in result.facts_used],
        "claims_unverified": result.claims_unverified,
        "constraints_check": result.constraints_check.model_dump(),
        "quality": result.quality.model_dump(),
        "merchant_view": {
            "summary_fr": _merchant_summary_fr(
                result.content_type, result.resource_id, result.quality.score
            ),
            "summary_en": (
                f"New {result.content_type.value} generated. "
                f"Quality score: {result.quality.score}/100."
            ),
            "why_this_change": (
                "Generated by GEO by Organically based on confirmed product facts and SEO signals."
            ),
            "expected_impact": (
                "Improved visibility in AI-powered and traditional search engines."
            ),
        },
        "decision_state": {
            "status": result.status.value,
            "blocked_reasons": blocked,
            "next_actions": next_actions,
        },
    }
