import type { LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { useFetcher, useLoaderData } from "@remix-run/react";
import { useEffect, useState } from "react";
import {
  Badge,
  Banner,
  BlockStack,
  Box,
  Button,
  Card,
  Collapsible,
  Divider,
  InlineStack,
  Link,
  Page,
  ProgressBar,
  Text,
  Thumbnail,
  Tooltip,
} from "@shopify/polaris";
import { authenticate } from "../shopify.server";
import { callBackendForShop } from "../lib/api.server";
import { getLocale, localizedPath, t, type Locale } from "../lib/i18n";
import {
  ValidationClicksChart,
  type ClicksSeriesPoint,
} from "../components/ValidationClicksChart";

interface GscMetrics {
  clicks: number;
  impressions: number;
  position: number;
}

interface Decomposition {
  primary_metric: string | null;
  direction: string;
  cause_fr: string;
  cause_en: string;
}

interface ProductAction {
  event_id: number;
  action_type: string;
  field: string;
  old_value: string;
  new_value: string;
  gsc_before: GscMetrics;
  gsc_after: GscMetrics | null;
  decomposition: Decomposition | null;
}

interface ValidationDate {
  date: string;
  j28_date: string;
  window_status: "complete" | "waiting" | "insufficient";
  window_message_fr: string;
  window_message_en: string;
  days_remaining: number;
  actions: ProductAction[];
  traffic_28d: GscMetrics | null;
}

interface ProductEntry {
  resource_id: string;
  resource_type: string;
  resource_title: string;
  latest_applied_at: string;
  reach_gained: number | null;
  clicks_gained: number | null;
  traffic_confidence: "strong" | "to_confirm" | "insufficient";
  validation_dates: ValidationDate[];
  total_actions: number;
  image_url?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  page_url?: string;
}

interface ClickEntry {
  google: number;
  ai: number | null;
  total: number;
  since: string;
  source: "ga4" | "gsc";
  series?: ClicksSeriesPoint[];
}

type ClicksMap = Record<string, ClickEntry>;

interface ClicksResponse {
  ga4_ready: boolean;
  computed_at: string;
  resources: ClicksMap;
}

interface LoaderData {
  locale: Locale;
  products: ProductEntry[];
  summary: { total_products: number; total_actions: number };
  clicks: ClicksMap;
  ga4Ready: boolean;
}

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const shop = session.shop;
  const locale = getLocale(request);

  let products: ProductEntry[] = [];
  let summary = { total_products: 0, total_actions: 0 };
  let clicks: ClicksMap = {};
  let ga4Ready = false;

  try {
    const resp = await callBackendForShop(
      shop,
      `/api/shops/${shop}/geo/analysis-overview`,
      { accessToken: session.accessToken },
    );
    if (resp.ok) {
      const data = await resp.json();
      products = data.products ?? [];
      summary = data.summary ?? summary;
    }
  } catch {
    // fail-open
  }

  try {
    const resp = await callBackendForShop(
      shop,
      `/api/shops/${shop}/geo/clicks-since-validation`,
      { accessToken: session.accessToken },
    );
    if (resp.ok) {
      const data = (await resp.json()) as ClicksResponse;
      clicks = data.resources ?? {};
      ga4Ready = data.ga4_ready ?? false;
    }
  } catch {
    // fail-open — counters just stay hidden
  }

  return json<LoaderData>({ locale, products, summary, clicks, ga4Ready });
};

function fieldLabel(field: string): string {
  const labels: Record<string, string> = {
    "seo.title": "Meta title",
    "seo.description": "Meta description",
    descriptionHtml: "Description produit",
    "metafield.custom.json_ld": "Schema JSON-LD",
  };
  return labels[field] ?? field;
}

function windowTone(status: string): "success" | "warning" | "critical" {
  if (status === "complete") return "success";
  if (status === "waiting") return "warning";
  return "critical";
}

function windowBadgeLabel(status: string, daysRemaining: number, locale: Locale): string {
  if (status === "complete") return locale === "fr" ? "28 j ✓" : "28 d ✓";
  if (status === "waiting") return locale === "fr" ? `J-${daysRemaining}` : `D-${daysRemaining}`;
  return locale === "fr" ? "< 28 j" : "< 28 d";
}

function confidenceTone(confidence: string): "success" | "warning" | undefined {
  if (confidence === "strong") return "success";
  if (confidence === "to_confirm") return "warning";
  return undefined;
}

function signed(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

/** Reach/clicks headline + dated 28-day validation entries for one resource. */
function EntryContent({ product, locale }: { product: ProductEntry; locale: Locale }) {
  return (
    <BlockStack gap="400">
      {/* Headline: reach + clicks generated by all modifications */}
      {product.reach_gained !== null && product.clicks_gained !== null ? (
        <Box padding="300" background="bg-surface-secondary" borderRadius="200">
          <BlockStack gap="200">
            <InlineStack gap="600" wrap blockAlign="center">
              <BlockStack gap="050">
                <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseReachGained")}</Text>
                <Text as="span" variant="heading2xl">{signed(product.reach_gained)}</Text>
              </BlockStack>
              <BlockStack gap="050">
                <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseClicksGained")}</Text>
                <Text as="span" variant="heading2xl">{signed(product.clicks_gained)}</Text>
              </BlockStack>
              <Badge tone={confidenceTone(product.traffic_confidence)}>
                {t(locale, `analyseConfidence_${product.traffic_confidence}`)}
              </Badge>
            </InlineStack>
            <Text as="p" variant="bodySm" tone="subdued">{t(locale, "analyseTrafficNote")}</Text>
          </BlockStack>
        </Box>
      ) : (
        <Text as="p" variant="bodySm" tone="subdued">{t(locale, "analyseTrafficPending")}</Text>
      )}

      {/* Validation dates for this resource */}
      {product.validation_dates.map((vd) => (
        <Box key={vd.date} padding="300" background="bg-surface-secondary" borderRadius="200">
          <BlockStack gap="200">
            <InlineStack gap="200" blockAlign="center" wrap>
              <Text as="h3" variant="headingSm">
                {t(locale, "analyseAppliedAt")} {vd.date}
              </Text>
              <Badge tone={windowTone(vd.window_status)}>
                {windowBadgeLabel(vd.window_status, vd.days_remaining, locale)}
              </Badge>
            </InlineStack>

            {vd.window_status === "waiting" && (
              <Banner tone="warning">
                <BlockStack gap="200">
                  <Text as="p">{locale === "fr" ? vd.window_message_fr : vd.window_message_en}</Text>
                  <ProgressBar
                    progress={Math.round(((28 - vd.days_remaining) / 28) * 100)}
                    tone="highlight"
                    size="small"
                  />
                </BlockStack>
              </Banner>
            )}

            {vd.window_status === "insufficient" && (
              <Banner tone="critical">
                <Text as="p">{locale === "fr" ? vd.window_message_fr : vd.window_message_en}</Text>
              </Banner>
            )}

            {vd.window_status === "complete" && vd.traffic_28d && (
              <>
                <Text as="span" variant="bodySm" tone="subdued">
                  {t(locale, "analyseJ28Date")}: {vd.j28_date}
                </Text>
                <InlineStack gap="600" wrap>
                  <BlockStack gap="050">
                    <Text as="span" variant="bodySm" tone="subdued">Impressions</Text>
                    <Text as="span" variant="headingSm">{vd.traffic_28d.impressions.toLocaleString("fr-FR")}</Text>
                  </BlockStack>
                  <BlockStack gap="050">
                    <Text as="span" variant="bodySm" tone="subdued">{t(locale, "measureColClicks")}</Text>
                    <Text as="span" variant="headingSm">{vd.traffic_28d.clicks.toLocaleString("fr-FR")}</Text>
                  </BlockStack>
                  <BlockStack gap="050">
                    <Text as="span" variant="bodySm" tone="subdued">{t(locale, "measureColPosition")}</Text>
                    <Text as="span" variant="headingSm">
                      {vd.traffic_28d.position > 0 ? vd.traffic_28d.position.toFixed(1) : "—"}
                    </Text>
                  </BlockStack>
                </InlineStack>
              </>
            )}

            {vd.actions.map((action) => (
              <Box key={action.event_id} padding="200" background="bg-surface-tertiary" borderRadius="100">
                <BlockStack gap="100">
                  <Badge>{fieldLabel(action.field)}</Badge>
                  {action.old_value ? (
                    <InlineStack gap="200">
                      <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseBefore")}</Text>
                      <Text as="span" variant="bodySm">{action.old_value}</Text>
                    </InlineStack>
                  ) : null}
                  {action.new_value ? (
                    <InlineStack gap="200">
                      <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseAfter")}</Text>
                      <Text as="span" variant="bodySm">{action.new_value}</Text>
                    </InlineStack>
                  ) : null}
                  {vd.window_status === "complete" && action.gsc_after ? (
                    <InlineStack gap="400" wrap>
                      <Text as="span" variant="bodySm">
                        Imp: {action.gsc_before.impressions} → {action.gsc_after.impressions}
                        {action.gsc_after.impressions !== action.gsc_before.impressions && (
                          <> ({action.gsc_after.impressions > action.gsc_before.impressions ? "+" : ""}
                          {action.gsc_after.impressions - action.gsc_before.impressions})</>
                        )}
                      </Text>
                      <Text as="span" variant="bodySm">
                        Pos: {action.gsc_before.position > 0 ? action.gsc_before.position.toFixed(1) : "—"} → {action.gsc_after.position > 0 ? action.gsc_after.position.toFixed(1) : "—"}
                      </Text>
                    </InlineStack>
                  ) : null}
                  {vd.window_status === "complete" && action.decomposition && action.decomposition.primary_metric ? (
                    <Text as="p" variant="bodySm" tone="subdued">
                      💡 {locale === "fr" ? action.decomposition.cause_fr : action.decomposition.cause_en}
                    </Text>
                  ) : null}
                </BlockStack>
              </Box>
            ))}
          </BlockStack>
        </Box>
      ))}
    </BlockStack>
  );
}

/** Collapsible header row with a chevron. */
function DropdownHeader({
  open, onToggle, title, count, countLabel,
}: { open: boolean; onToggle: () => void; title: string; count: number; countLabel: string }) {
  return (
    <Button onClick={onToggle} fullWidth textAlign="left" disclosure={open ? "up" : "down"} variant="tertiary">
      {`${title} (${count} ${countLabel})`}
    </Button>
  );
}

/** Live "X clics depuis le … (Google · IA)" line shown under a validated title. */
function ClicksLine({ entry, locale }: { entry: ClickEntry | undefined; locale: Locale }) {
  if (!entry) return null;
  const since = new Date(`${entry.since}T00:00:00`).toLocaleDateString(
    locale === "fr" ? "fr-FR" : "en-US",
    { day: "2-digit", month: "short", year: "numeric" },
  );
  const tooltip = entry.source === "ga4"
    ? t(locale, "analyseClicksTooltipGa4")
    : t(locale, "analyseClicksTooltipGsc");
  return (
    <InlineStack gap="150" blockAlign="center" wrap>
      <Tooltip content={tooltip}>
        <Text as="span" variant="bodySm" tone="subdued">
          {`👁 ${entry.total.toLocaleString(locale === "fr" ? "fr-FR" : "en-US")} ${t(locale, "analyseClicksLabel")} ${t(locale, "analyseClicksSince")} ${since}`}
        </Text>
      </Tooltip>
    </InlineStack>
  );
}

/** When a validated resource has 0 clicks, prompt to check indexing on Google. */
function ZeroClicksHint({
  entry, pageUrl, locale,
}: { entry: ClickEntry | undefined; pageUrl?: string; locale: Locale }) {
  if (!entry || entry.total !== 0 || !pageUrl) return null;
  const googleUrl = `https://www.google.com/search?q=${encodeURIComponent(`site:${pageUrl}`)}`;
  // App Bridge intercepts <a target="_blank"> and loads external URLs inside the
  // embedded iframe (Google refuses framing). window.open breaks out to a real tab.
  return (
    <InlineStack gap="150" blockAlign="center" wrap>
      <Text as="span" variant="bodySm" tone="subdued">
        ⚠️ {t(locale, "analyseZeroClicksHint")}
      </Text>
      <Button
        variant="plain"
        onClick={() => window.open(googleUrl, "_blank", "noopener,noreferrer")}
      >
        {t(locale, "analyseZeroClicksCheck")}
      </Button>
    </InlineStack>
  );
}

export default function AnalysePage() {
  const { locale, products, summary, clicks: initialClicks, ga4Ready: initialGa4Ready } =
    useLoaderData<typeof loader>() as LoaderData;
  const blogs = products.filter((p) => p.resource_type === "blog_post");
  const prods = products.filter((p) => p.resource_type !== "blog_post");
  const [showBlogs, setShowBlogs] = useState(false);
  const [showProducts, setShowProducts] = useState(false);
  const [openIds, setOpenIds] = useState<Set<string>>(new Set());

  // Live click counters: seeded from the loader, then auto-refreshed by polling
  // the lightweight resource route every 60 s (and when the tab regains focus).
  const [clicks, setClicks] = useState<ClicksMap>(initialClicks);
  const [ga4Ready, setGa4Ready] = useState(initialGa4Ready);
  const clicksFetcher = useFetcher<ClicksResponse>();

  useEffect(() => {
    const reload = () => clicksFetcher.load("/app/clicks-since-validation");
    const id = setInterval(reload, 60_000);
    const onFocus = () => {
      if (document.visibilityState === "visible") reload();
    };
    document.addEventListener("visibilitychange", onFocus);
    return () => {
      clearInterval(id);
      document.removeEventListener("visibilitychange", onFocus);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (clicksFetcher.data?.resources) {
      setClicks(clicksFetcher.data.resources);
      setGa4Ready(clicksFetcher.data.ga4_ready ?? false);
    }
  }, [clicksFetcher.data]);

  const toggleId = (id: string) =>
    setOpenIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });

  return (
    <Page
      title={t(locale, "analyseTitle")}
      subtitle={t(locale, "analyseSubtitle")}
      backAction={{ content: t(locale, "backDashboard"), url: localizedPath("/app", locale) }}
      secondaryActions={[
        { content: t(locale, "measureNav"), url: localizedPath("/app/measure", locale) },
      ]}
    >
      <BlockStack gap="400">
        <Card>
          <InlineStack gap="600" wrap>
            <BlockStack gap="050">
              <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseProductsOptimized")}</Text>
              <Text as="span" variant="headingLg">{summary.total_products}</Text>
            </BlockStack>
            <BlockStack gap="050">
              <Text as="span" variant="bodySm" tone="subdued">{t(locale, "analyseTotalActions")}</Text>
              <Text as="span" variant="headingLg">{summary.total_actions}</Text>
            </BlockStack>
          </InlineStack>
        </Card>

        {products.length > 0 && !ga4Ready && (
          <Banner tone="info">
            <InlineStack gap="100" wrap>
              <Text as="span">{t(locale, "analyseClicksConnectGa4")}</Text>
              <Link url={localizedPath("/app/account", locale)}>
                {t(locale, "analyseClicksConnectGa4Cta")}
              </Link>
            </InlineStack>
          </Banner>
        )}

        {products.length === 0 ? (
          <Card>
            <Text as="p" tone="subdued">{t(locale, "analyseEmpty")}</Text>
          </Card>
        ) : (
          <>
            {/* ── Produits dropdown, with a sub-dropdown per product ──── */}
            {prods.length > 0 && (
              <Card>
                <BlockStack gap="300">
                  <DropdownHeader
                    open={showProducts}
                    onToggle={() => setShowProducts((o) => !o)}
                    title={locale === "fr" ? "Produits" : "Products"}
                    count={prods.length}
                    countLabel={locale === "fr" ? "produits" : "products"}
                  />
                  <Collapsible open={showProducts} id="analyse-products">
                    <BlockStack gap="200">
                      {prods.map((product) => {
                        const isOpen = openIds.has(product.resource_id);
                        const entry = clicks[product.resource_id];
                        return (
                          <Card key={product.resource_id}>
                            <BlockStack gap="300">
                              <InlineStack gap="300" blockAlign="start" wrap={false}>
                                {product.image_url ? (
                                  <Thumbnail
                                    source={product.image_url}
                                    alt={product.resource_title}
                                    size="large"
                                  />
                                ) : (
                                  <Box
                                    background="bg-surface-secondary"
                                    borderRadius="200"
                                    minWidth="80px"
                                    minHeight="80px"
                                  />
                                )}
                                <BlockStack gap="100">
                                  <Text as="h3" variant="headingMd">{product.resource_title}</Text>
                                  {product.meta_title ? (
                                    <Text as="p" variant="bodyMd">{product.meta_title}</Text>
                                  ) : null}
                                  {product.meta_description ? (
                                    <Text as="p" variant="bodySm" tone="subdued">
                                      {product.meta_description}
                                    </Text>
                                  ) : null}
                                </BlockStack>
                              </InlineStack>

                              <ClicksLine entry={entry} locale={locale} />
                              <ZeroClicksHint entry={entry} pageUrl={product.page_url} locale={locale} />

                              <ValidationClicksChart
                                series={entry?.series ?? []}
                                label={t(locale, "analyseChartTitle")}
                                emptyLabel={t(locale, "analyseChartNeedsGa4")}
                                locale={locale}
                              />

                              <Button
                                onClick={() => toggleId(product.resource_id)}
                                textAlign="left"
                                disclosure={isOpen ? "up" : "down"}
                                variant="tertiary"
                              >
                                {`${t(locale, "analyseMoreDetails")} (${product.total_actions} ${t(locale, "analyseActionsCount")})`}
                              </Button>
                              <Collapsible open={isOpen} id={`analyse-product-${product.resource_id}`}>
                                <EntryContent product={product} locale={locale} />
                              </Collapsible>
                            </BlockStack>
                          </Card>
                        );
                      })}
                    </BlockStack>
                  </Collapsible>
                </BlockStack>
              </Card>
            )}

            {/* ── Blogs dropdown ─────────────────────────────────────── */}
            {blogs.length > 0 && (
              <Card>
                <BlockStack gap="300">
                  <DropdownHeader
                    open={showBlogs}
                    onToggle={() => setShowBlogs((o) => !o)}
                    title={locale === "fr" ? "Blogs" : "Blogs"}
                    count={blogs.length}
                    countLabel={locale === "fr" ? "articles" : "articles"}
                  />
                  <Collapsible open={showBlogs} id="analyse-blogs">
                    <BlockStack gap="300">
                      {blogs.map((blog, i) => {
                        const isOpen = openIds.has(blog.resource_id);
                        return (
                          <BlockStack key={blog.resource_id} gap="300">
                            {i > 0 && <Divider />}
                            <InlineStack gap="200" blockAlign="center" wrap>
                              <Text as="h2" variant="headingMd">{blog.resource_title}</Text>
                              <Text as="span" variant="bodySm" tone="subdued">
                                {blog.total_actions} {t(locale, "analyseActionsCount")}
                              </Text>
                            </InlineStack>
                            <ClicksLine entry={clicks[blog.resource_id]} locale={locale} />
                            <ZeroClicksHint
                              entry={clicks[blog.resource_id]}
                              pageUrl={blog.page_url}
                              locale={locale}
                            />
                            <Button
                              onClick={() => toggleId(blog.resource_id)}
                              textAlign="left"
                              disclosure={isOpen ? "up" : "down"}
                              variant="tertiary"
                            >
                              {t(locale, "analyseMoreDetails")}
                            </Button>
                            <Collapsible open={isOpen} id={`analyse-blog-${blog.resource_id}`}>
                              <EntryContent product={blog} locale={locale} />
                            </Collapsible>
                          </BlockStack>
                        );
                      })}
                    </BlockStack>
                  </Collapsible>
                </BlockStack>
              </Card>
            )}
          </>
        )}

        {/* Bottom breathing room so the last panel isn't glued to the page edge. */}
        <Box paddingBlockEnd="800" />
      </BlockStack>
    </Page>
  );
}
