"""Analysis overview — grouped by product, then by validation date.

For each product, lists validation dates chronologically. For each date:
- "complete": 28 days passed before the next validation on this product → show GSC traffic
- "waiting": last validation on this product and < 28 days elapsed → show countdown
- "insufficient": new validation on this product happened before 28 days → flag
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from app.db_adapter import DB_PATH
from app.geo.ledger import list_geo_events
from app.impact.report import _find_gsc_file, _parse_gsc_csv
from app.learning.outcomes import calculate_outcome

logger = logging.getLogger(__name__)


def _gsc_traffic_for_path(
    resource_path: str,
    gsc_rows: dict[str, dict],
) -> dict[str, Any]:
    empty = {"clicks": 0, "impressions": 0, "ctr": 0.0, "position": 0.0}
    if not resource_path:
        return empty
    target = resource_path.rstrip("/")
    for url, row in gsc_rows.items():
        if url.rstrip("/").endswith(target):
            return {
                "clicks": int(row.get("clicks", 0) or 0),
                "impressions": int(row.get("impressions", 0) or 0),
                "ctr": round(float(row.get("ctr", 0.0) or 0.0), 4),
                "position": round(float(row.get("position", 0.0) or 0.0), 1),
            }
    return empty


def _parse_date(iso_str: str) -> datetime | None:
    if not iso_str:
        return None
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.astimezone(UTC) if dt.tzinfo else dt.replace(tzinfo=UTC)
    except (ValueError, AttributeError):
        return None


def _extract_applied_at(event: dict[str, Any]) -> str:
    for entry in event.get("status_history") or []:
        if entry.get("status") in {"applied", "measured"}:
            return entry.get("changed_at") or event.get("created_at", "")
    return event.get("created_at", "")


def _traffic_generated(
    baseline: dict[str, Any] | None,
    latest_after: dict[str, Any] | None,
) -> tuple[int | None, int | None, str]:
    """Compute reach + clicks generated by all modifications, with a confidence label.

    Combines SEO and GEO into one organic figure (the product URL's GSC delta
    between the first application baseline and the latest J+28 measurement).
    Returns (reach_gained, clicks_gained, confidence) where confidence is one of
    "strong" | "to_confirm" | "insufficient".
    """
    if baseline is None or latest_after is None:
        return None, None, "insufficient"

    before = baseline["gsc"]
    after = latest_after["gsc"]
    imp_before = int(before.get("impressions", 0) or 0)
    imp_after = int(after.get("impressions", 0) or 0)
    clk_before = int(before.get("clicks", 0) or 0)
    clk_after = int(after.get("clicks", 0) or 0)

    reach_gained = imp_after - imp_before
    clicks_gained = clk_after - clk_before

    # Confidence from baseline volume: too few impressions = noisy read.
    if imp_before < 50 and imp_after < 50:
        confidence = "insufficient"
    elif imp_before >= 200 or imp_after >= 200:
        confidence = "strong"
    else:
        confidence = "to_confirm"
    return reach_gained, clicks_gained, confidence


def _truncate(value: Any, max_len: int = 120) -> str:
    s = str(value or "")
    if len(s) > max_len:
        return s[:max_len] + "…"
    return s


def _window_status_for_date(
    applied_dt: datetime,
    next_dt: datetime | None,
    now: datetime,
) -> dict[str, Any]:
    """Compute the 28-day window status for a single validation date on one product."""
    j28_dt = applied_dt + timedelta(days=28)
    j28_date = j28_dt.strftime("%Y-%m-%d")

    if next_dt is not None:
        days_to_next = (next_dt - applied_dt).days
        if days_to_next < 28:
            return {
                "j28_date": j28_date,
                "window_status": "insufficient",
                "days_remaining": 0,
                "days_to_next": days_to_next,
                "window_message_fr": "Modifié à nouveau en moins de 28 j — pas assez de recul pour mesurer l'impact",
                "window_message_en": "Modified again within 28 d — not enough time to measure impact",
            }
        return {
            "j28_date": j28_date,
            "window_status": "complete",
            "days_remaining": 0,
            "days_to_next": days_to_next,
            "window_message_fr": "Fenêtre de 28 jours complète",
            "window_message_en": "28-day window complete",
        }

    elapsed = (now - applied_dt).days
    if elapsed >= 28:
        return {
            "j28_date": j28_date,
            "window_status": "complete",
            "days_remaining": 0,
            "days_to_next": None,
            "window_message_fr": "Fenêtre de 28 jours complète",
            "window_message_en": "28-day window complete",
        }
    days_remaining = 28 - elapsed
    return {
        "j28_date": j28_date,
        "window_status": "waiting",
        "days_remaining": days_remaining,
        "days_to_next": None,
        "window_message_fr": f"Encore {days_remaining} jour{'s' if days_remaining > 1 else ''} avant la mesure J+28",
        "window_message_en": f"{days_remaining} day{'s' if days_remaining > 1 else ''} remaining until J+28 measurement",
    }


def _product_meta_index(shop: str, db_path: Path | None) -> dict[str, dict[str, Any]]:
    """Map product gid -> {image_url, meta_title, meta_description} from the latest snapshot.

    The analysis overview only knows validation events; the product card on the
    Analyse page also needs the current image and SEO meta, which live in the snapshot.
    """
    from app.api.snapshot_store import load_latest_snapshot_from_db  # noqa: PLC0415

    data = load_latest_snapshot_from_db(shop, db_path=db_path)
    if not data:
        return {}

    index: dict[str, dict[str, Any]] = {}
    for product in data.get("products", []):
        gid = str(product.get("id") or "")
        if not gid:
            continue
        image_url: str | None = None
        images = product.get("images") or {}
        edges = images.get("edges", []) if isinstance(images, dict) else []
        if edges and isinstance(edges[0], dict):
            node = edges[0].get("node", {})
            image_url = node.get("url") or node.get("src")
        seo = product.get("seo") or {}
        index[gid] = {
            "image_url": image_url,
            "meta_title": seo.get("title"),
            "meta_description": seo.get("description"),
        }
    return index


def build_analysis_overview(
    shop: str,
    *,
    db_path: Path | None = None,
) -> dict[str, Any]:
    """Build analysis grouped by product, then by validation date.

    Returns:
        Dict with ``products`` list and ``summary``.
    """
    path = db_path or DB_PATH
    now = datetime.now(UTC)

    events_data = list_geo_events(shop, limit=200, status="applied", db_path=path)
    events = events_data["events"]
    measured_data = list_geo_events(shop, limit=200, status="measured", db_path=path)
    events.extend(measured_data["events"])

    gsc_file = _find_gsc_file(shop)
    gsc_rows = _parse_gsc_csv(gsc_file.read_text()) if gsc_file else {}

    meta_index = _product_meta_index(shop, path)

    # Blog articles the merchant has since deleted (no matching draft) must drop
    # off the analysis page. Valid blog ids = current drafts' Shopify article id
    # (plus the draft id, used as a fallback resource id at publish time).
    valid_blog_ids: set[str] = set()
    try:
        from app.blog.store import list_drafts  # noqa: PLC0415

        for draft in list_drafts(shop):
            for key in ("shopify_article_id", "id"):
                value = str(draft.get(key) or "").strip()
                if value:
                    valid_blog_ids.add(value)
    except Exception:  # pragma: no cover - blog store optional/empty
        valid_blog_ids = set()

    # Group events by product, then by date
    products_map: dict[str, dict[str, Any]] = {}

    for event in events:
        rid = event["resource_id"]
        if rid not in products_map:
            before_snapshot = event.get("before_snapshot") or {}
            resource_path = before_snapshot.get("path", "")
            products_map[rid] = {
                "resource_id": rid,
                "resource_type": event["resource_type"],
                "resource_title": event["resource_title"],
                "resource_path": resource_path,
                "dates_map": {},
                "latest_applied_at": "",
            }

        product = products_map[rid]
        applied_at = _extract_applied_at(event)
        date_key = applied_at[:10]
        if not date_key:
            continue

        if date_key > product["latest_applied_at"]:
            product["latest_applied_at"] = date_key

        if date_key not in product["dates_map"]:
            product["dates_map"][date_key] = []

        before_snapshot = event.get("before_snapshot") or {}
        after_snapshot = event.get("after_snapshot") or {}
        metrics_before = (event.get("metrics_before") or {}).get("gsc") or {}
        metrics_after = (event.get("metrics_after") or {}).get("gsc") or {}
        field = after_snapshot.get("field", event["action_type"])

        decomposition = None
        if metrics_after:
            outcome = calculate_outcome(
                before_metrics={"gsc": metrics_before},
                after_metrics={"gsc": metrics_after},
                field=field,
                action_type=event["action_type"],
            )
            decomposition = outcome.get("decomposition")

        product["dates_map"][date_key].append({
            "event_id": event["id"],
            "action_type": event["action_type"],
            "field": field,
            "old_value": _truncate(
                before_snapshot.get("content", {}).get(after_snapshot.get("field", ""), "")
            ),
            "new_value": _truncate(after_snapshot.get("value", "")),
            "gsc_before": {
                "clicks": int(metrics_before.get("clicks", 0) or 0),
                "impressions": int(metrics_before.get("impressions", 0) or 0),
                "position": round(float(metrics_before.get("position", 0.0) or 0.0), 1),
            },
            "gsc_after": {
                "clicks": int(metrics_after.get("clicks", 0) or 0),
                "impressions": int(metrics_after.get("impressions", 0) or 0),
                "position": round(float(metrics_after.get("position", 0.0) or 0.0), 1),
            } if metrics_after else None,
            "decomposition": decomposition,
        })

        # Track product-level baseline (earliest) and latest measured "after"
        # to compute reach/clicks generated by all modifications combined.
        if metrics_before:
            baseline = product.setdefault("_baseline", {"date": date_key, "gsc": metrics_before})
            if date_key <= baseline["date"]:
                product["_baseline"] = {"date": date_key, "gsc": metrics_before}
        if metrics_after:
            latest = product.get("_latest_after")
            if latest is None or date_key >= latest["date"]:
                product["_latest_after"] = {"date": date_key, "gsc": metrics_after}

    # Build final product list with dated validation entries
    product_list: list[dict[str, Any]] = []

    for product in products_map.values():
        # Hide blog articles the merchant deleted (no matching draft remains).
        if product["resource_type"] == "blog_post" and product["resource_id"] not in valid_blog_ids:
            continue
        dates_map = product.pop("dates_map")
        baseline = product.pop("_baseline", None)
        latest_after = product.pop("_latest_after", None)
        sorted_date_keys = sorted(dates_map.keys())

        validation_dates: list[dict[str, Any]] = []
        for i, date_key in enumerate(sorted_date_keys):
            applied_dt = _parse_date(date_key)
            if applied_dt is None:
                continue

            is_last = i == len(sorted_date_keys) - 1
            next_date_key = sorted_date_keys[i + 1] if not is_last else None
            next_dt = _parse_date(next_date_key) if next_date_key else None

            window = _window_status_for_date(applied_dt, next_dt, now)

            show_traffic = window["window_status"] == "complete"
            traffic_28d = _gsc_traffic_for_path(product["resource_path"], gsc_rows) if show_traffic else None

            validation_dates.append({
                "date": date_key,
                "actions": dates_map[date_key],
                "traffic_28d": traffic_28d,
                **window,
            })

        # Most recent date first within each product
        validation_dates.reverse()

        reach_gained, clicks_gained, traffic_confidence = _traffic_generated(
            baseline, latest_after
        )

        meta = meta_index.get(product["resource_id"], {})
        product_list.append({
            "resource_id": product["resource_id"],
            "resource_type": product["resource_type"],
            "resource_title": product["resource_title"],
            "resource_path": product["resource_path"],
            "latest_applied_at": product["latest_applied_at"],
            "reach_gained": reach_gained,
            "clicks_gained": clicks_gained,
            "traffic_confidence": traffic_confidence,
            "validation_dates": validation_dates,
            "total_actions": sum(len(d["actions"]) for d in validation_dates),
            "image_url": meta.get("image_url"),
            "meta_title": meta.get("meta_title"),
            "meta_description": meta.get("meta_description"),
        })

    # Most recently optimized product first
    product_list.sort(key=lambda p: p["latest_applied_at"], reverse=True)

    return {
        "products": product_list,
        "summary": {
            "total_products": len(product_list),
            "total_actions": sum(p["total_actions"] for p in product_list),
        },
    }
