"""AI crawlability and llms.txt preview for Shopify catalogs."""

from __future__ import annotations

from typing import Any

from app.geo._shared import (
    POLICY_PATHS,
    absolute_url,
    collection_rows,
    product_rows,
    resource_row,
    shop_domain,
)

_AI_ROBOTS_TEMPLATE = """{% for group in robots.default_groups %}
  {{- group.user_agent }}
  {% for rule in group.rules %}
    {{- rule }}
  {% endfor %}
  {%- if group.sitemap != blank -%}
    {{ group.sitemap }}
  {%- endif -%}
{% endfor %}

# AI discovery crawlers
User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /
"""


def _llms_text(domain: str, included: list[dict[str, str]], excluded: list[dict[str, str]]) -> str:
    lines = [
        "# llms.txt preview",
        f"# Site: https://{domain}",
        "# Generated by Leonie SEO as a preview. Review before publishing.",
        "",
        "## Recommended pages",
    ]
    for row in included:
        lines.append(f"- [{row['title']}]({absolute_url(domain, row['path'])}): {row['reason']}")
    lines.extend(["", "## Pages to review or exclude"])
    for row in excluded:
        target = absolute_url(domain, row["path"]) if row["path"] else "missing-url"
        lines.append(f"- {row['title']} ({target}): {row['reason']}")
    lines.extend(
        [
            "",
            "## Notes",
            "- This preview is guidance for AI crawlers and does not guarantee ranking, citations, or traffic.",
            "- Publish only after merchant review and after excluding private, cart, checkout, account, and search URLs.",
        ]
    )
    return "\n".join(lines)


def build_ai_crawlability_advisor(
    shop: str,
    snapshot: dict[str, Any],
    *,
    top_products: int = 30,
    top_collections: int = 20,
) -> dict[str, Any]:
    """Build an llms.txt preview and AI crawlability recommendations."""
    domain = shop_domain(shop, snapshot)
    included_products, product_excluded = product_rows(snapshot.get("products", []))
    included_collections, collection_excluded = collection_rows(snapshot.get("collections", []))
    policy_rows = [
        resource_row(
            resource_type="policy",
            title=title,
            path=path,
            reason="Policy or trust page helps AI systems understand merchant terms and support context.",
            priority="medium",
        )
        for path, title in POLICY_PATHS
    ]

    included = (
        policy_rows + included_collections[:top_collections] + included_products[:top_products]
    )
    excluded = product_excluded + collection_excluded
    warnings = []
    if not included_products:
        warnings.append("No product page is ready enough to recommend in llms.txt preview.")
    if len(product_excluded) > 0:
        warnings.append(
            "Some product pages have thin copy or missing handles and should be reviewed first."
        )
    if not included_collections:
        warnings.append("No collection page could be listed from the current snapshot.")

    return {
        "domain": domain,
        "summary": {
            "included_pages": len(included),
            "excluded_or_review_pages": len(excluded),
            "product_pages": len([row for row in included if row["resource_type"] == "product"]),
            "collection_pages": len(
                [row for row in included if row["resource_type"] == "collection"]
            ),
            "policy_pages": len([row for row in included if row["resource_type"] == "policy"]),
            "dry_run": True,
            "note": "llms.txt is treated as emerging AI crawl guidance, not a ranking or citation guarantee.",
        },
        "included_pages": included,
        "excluded_pages": excluded,
        "warnings": warnings,
        "llms_txt": _llms_text(domain, included, excluded),
        "robots_txt_liquid": _AI_ROBOTS_TEMPLATE,
        "robots_install_steps": [
            "Online Store > Themes > Edit code",
            "Templates > Add a new template > robots.txt",
            "Paste this content, save, then open /robots.txt to verify the AI crawler groups.",
        ],
    }
