"""AI crawlability and llms.txt preview for Shopify catalogs."""

from __future__ import annotations

import re
from typing import Any

from app.geo.readiness import score_product_readiness

_POLICY_PATHS = (
    ("/policies/privacy-policy", "Privacy policy"),
    ("/policies/refund-policy", "Refund policy"),
    ("/policies/shipping-policy", "Shipping policy"),
    ("/pages/contact", "Contact"),
)


def _strip_html(value: str | None) -> str:
    return re.sub(r"<[^>]+>", " ", value or "").strip()


def _description(product: dict[str, Any]) -> str:
    return _strip_html(
        product.get("descriptionHtml")
        or product.get("body_html")
        or product.get("description")
        or ""
    )


def _shop_domain(shop: str, snapshot: dict[str, Any]) -> str:
    domain = str(snapshot.get("shop", {}).get("domain") or shop).strip()
    return domain.replace("https://", "").replace("http://", "").strip("/")


def _url(domain: str, path: str) -> str:
    return f"https://{domain}{path}"


def _resource_row(
    *,
    resource_type: str,
    title: str,
    path: str,
    reason: str,
    priority: str,
) -> dict[str, str]:
    return {
        "resource_type": resource_type,
        "title": title,
        "path": path,
        "reason": reason,
        "priority": priority,
    }


def _product_rows(products: list[dict[str, Any]]) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    included: list[dict[str, str]] = []
    excluded: list[dict[str, str]] = []
    scored = []
    for product in products:
        title = str(product.get("title") or "").strip()
        handle = str(product.get("handle") or "").strip()
        if not title or not handle:
            excluded.append(
                _resource_row(
                    resource_type="product",
                    title=title or "Untitled product",
                    path="",
                    reason="Missing title or handle, so the page cannot be safely listed.",
                    priority="exclude",
                )
            )
            continue
        readiness = score_product_readiness(product)
        description_words = len(_description(product).split())
        if description_words < 8:
            excluded.append(
                _resource_row(
                    resource_type="product",
                    title=title,
                    path=f"/products/{handle}",
                    reason="Product copy is too thin for useful AI crawl guidance.",
                    priority="review",
                )
            )
            continue
        scored.append((readiness["readiness_score"], title, handle))

    scored.sort(key=lambda item: (-item[0], item[1]))
    for score, title, handle in scored:
        priority = "high" if score >= 70 else "medium" if score >= 45 else "review"
        included.append(
            _resource_row(
                resource_type="product",
                title=title,
                path=f"/products/{handle}",
                reason=f"Product page with AI Search readiness {score}/100.",
                priority=priority,
            )
        )
    return included, excluded


def _collection_rows(collections: list[dict[str, Any]]) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    included: list[dict[str, str]] = []
    excluded: list[dict[str, str]] = []
    for collection in collections:
        title = str(collection.get("title") or "").strip()
        handle = str(collection.get("handle") or "").strip()
        if not title or not handle:
            excluded.append(
                _resource_row(
                    resource_type="collection",
                    title=title or "Untitled collection",
                    path="",
                    reason="Missing title or handle, so the collection cannot be safely listed.",
                    priority="exclude",
                )
            )
            continue
        included.append(
            _resource_row(
                resource_type="collection",
                title=title,
                path=f"/collections/{handle}",
                reason="Collection page can help AI crawlers understand product grouping and buying intent.",
                priority="medium",
            )
        )
    included.sort(key=lambda item: item["title"])
    return included, excluded


def _llms_text(domain: str, included: list[dict[str, str]], excluded: list[dict[str, str]]) -> str:
    lines = [
        "# llms.txt preview",
        f"# Site: https://{domain}",
        "# Generated by Leonie SEO as a preview. Review before publishing.",
        "",
        "## Recommended pages",
    ]
    for row in included:
        lines.append(f"- [{row['title']}]({_url(domain, row['path'])}): {row['reason']}")
    lines.extend(["", "## Pages to review or exclude"])
    for row in excluded:
        target = _url(domain, row["path"]) if row["path"] else "missing-url"
        lines.append(f"- {row['title']} ({target}): {row['reason']}")
    lines.extend(
        [
            "",
            "## Notes",
            "- This preview is guidance for AI crawlers and does not guarantee ranking, citations, or traffic.",
            "- Publish only after merchant review and after excluding private, cart, checkout, account, and search URLs.",
        ]
    )
    return "\n".join(lines)


def build_ai_crawlability_advisor(
    shop: str,
    snapshot: dict[str, Any],
    *,
    top_products: int = 30,
    top_collections: int = 20,
) -> dict[str, Any]:
    """Build an llms.txt preview and AI crawlability recommendations."""
    domain = _shop_domain(shop, snapshot)
    product_rows, product_excluded = _product_rows(snapshot.get("products", []))
    collection_rows, collection_excluded = _collection_rows(snapshot.get("collections", []))
    policy_rows = [
        _resource_row(
            resource_type="policy",
            title=title,
            path=path,
            reason="Policy or trust page helps AI systems understand merchant terms and support context.",
            priority="medium",
        )
        for path, title in _POLICY_PATHS
    ]

    included = policy_rows + collection_rows[:top_collections] + product_rows[:top_products]
    excluded = product_excluded + collection_excluded
    warnings = []
    if not product_rows:
        warnings.append("No product page is ready enough to recommend in llms.txt preview.")
    if len(product_excluded) > 0:
        warnings.append("Some product pages have thin copy or missing handles and should be reviewed first.")
    if not collection_rows:
        warnings.append("No collection page could be listed from the current snapshot.")

    return {
        "domain": domain,
        "summary": {
            "included_pages": len(included),
            "excluded_or_review_pages": len(excluded),
            "product_pages": len([row for row in included if row["resource_type"] == "product"]),
            "collection_pages": len([row for row in included if row["resource_type"] == "collection"]),
            "policy_pages": len([row for row in included if row["resource_type"] == "policy"]),
            "dry_run": True,
            "note": "llms.txt is treated as emerging AI crawl guidance, not a ranking or citation guarantee.",
        },
        "included_pages": included,
        "excluded_pages": excluded,
        "warnings": warnings,
        "llms_txt": _llms_text(domain, included, excluded),
    }
