name = "Léonie SEO"
client_id = "53ff34f2abe2ab7e3a2cd334fbd84db8"
application_url = "https://localhost:3458"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_content"

[auth]
redirect_urls = [
  "https://localhost:3458/auth/callback",
  "https://localhost:3458/auth/shopify/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback",
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]
  uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
